modLoader="javafml"
loaderVersion="[43,)"
license="Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Protect-Your-Moa/issues"

[[mods]]
modId="aether_protect_your_moa"
version="${file.jarVersion}"
displayName="Protect Your Moa"
updateJSONURL="https://github.com/The-Aether-Team/Protect-Your-Moa/raw/1.20.1-develop/update.json"
displayURL="https://modrinth.com/mod/aether-protect-your-moa"
logoFile="protect_your_moa_icon.png"
credits="The Aether Team"
authors="bconlon, Oz Payn"
description='''TBA.'''

[[dependencies.aether_protect_your_moa]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aether_protect_your_moa]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.19.2-1.4.2-forge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_protect_your_moa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
