modLoader="javafml"
loaderVersion="[1,)"
license="Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Protect-Your-Moa/issues"

[[mods]]
modId="aether_protect_your_moa"
version="${file.jarVersion}"
displayName="Protect Your Moa"
updateJSONURL="https://github.com/The-Aether-Team/Protect-Your-Moa/raw/1.20.1-develop/update.json"
displayURL="https://modrinth.com/mod/aether-protect-your-moa"
logoFile="protect_your_moa_icon.png"
credits="The Aether Team"
authors="bconlon, Oz Payn"
description='''TBA.'''

[[dependencies.aether_protect_your_moa]]
    modId="neoforge"
    type = "required"
    versionRange="[20.4.167,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aether_protect_your_moa]]
    modId = "aether"
    type = "required"
    versionRange = "[1.20.4-1.4.1-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_protect_your_moa]]
    modId="minecraft"
    type = "required"
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="aether_protect_your_moa.mixins.json"