modLoader="javafml"
loaderVersion="[4,)"
license="Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Protect-Your-Moa/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="Protect Your Moa"
    updateJSONURL="https://github.com/The-Aether-Team/Protect-Your-Moa/raw/1.20.4-develop/update.json"
    displayURL="https://modrinth.com/mod/aether-protect-your-moa"
    logoFile="protect_your_moa_icon.png"
    credits="The Aether Team"
    authors="bconlon, Oz Payn"
    description='''
        An addon centered around equipment for Moas, allowing them to be outfitted with chests and craftable Moa Armor.
    '''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange="${mc_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "aether"
    type = "required"
    versionRange = "[1.5.0,)"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config="aether_protect_your_moa.mixins.json"