modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="https://github.com/The-Aether-Team/Protect-Your-Moa/issues"

[[mods]]
    modId = "aether_protect_your_moa"
    version = "1.0.0"
    displayName = "Protect Your Moa"
    updateJSONURL = "https://github.com/The-Aether-Team/Protect-Your-Moa/raw/1.21.1-develop/update.json"
    displayURL = "https://modrinth.com/mod/aether-protect-your-moa"
    logoFile = "aether_protect_your_moa.png"
    credits = "The Aether Team"
    authors = "bconlon, Oz Payn"
    description = '''An addon centered around equipment for Moas, allowing them to be outfitted with chests and craftable Moa Armor.'''

[[dependencies.aether_protect_your_moa]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.aether_protect_your_moa]]
    modId = "minecraft"
    type = "required"
    versionRange="${mc_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.aether_protect_your_moa]]
    modId = "aether"
    type = "required"
    versionRange = "[1.5.0,)"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "aether_protect_your_moa.mixins.json"