modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_tracker}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    updateJSONURL = "${mod_update}"
    displayURL = "${mod_url}"
    logoFile = "${mod_id}.png"
    credits = "${mod_credits}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "aether"
    type = "required"
    versionRange = "${aether_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange="${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config="aether_protect_your_moa.mixins.json"